services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrapy_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapy_container
    depends_on:
      - db
    volumes:
      - ./hotel_images:/app/hotel_images
      - ./logs:/app/logs
    environment:
      DATABASE_URL: "postgresql://user:password@postgres_container:5432/scrapy_db"
    command: ["sh", "-c", "scrapy crawl hotel_details_spider; sleep infinity"]
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
